### PR TITLE
Created cross building environment for amd64 and arm32v7

### PR DESCRIPTION
**Pull request by hansmp**
Added build environment to build amd64 and arm32v7 version of base container. Just call build.sh. Make sure to login first to docker-hub. This utilities QEMU as cross-building environment. AMD64 is build native.

### CODE REVIEW

**Comment by hansmp** [comment]
Added travis build environment. Make sure to set DOCKER_PASSWORD and DOCKER_USERNAME as travis env params. 
The system will build for branch master (reults in latest container) and develop (results in testing container) with pushing the images to dockerhub. For any PR the push is omitted.

**Comment by ChristianMayer** [comment]
Is the PowerShell (*.ps1) file needed?

**Comment by hansmp** [comment]
No. The powershell is only a helper to build the container in a windows environment (e.g. for development purposes). I've used it for primary development and finished it on a unix machine. We can drop it to keep the repo clean.

**Comment by hansmp** [comment]
Shall I remove it?

**Comment by ChristianMayer** [comment]
Yes I'd prefer it without it

**Comment by hansmp** [comment]
Done.

**Comment by hansmp** [comment]
Ah - i forgot to mention, that the comtainer generation will run about 30 minutes. So don't wonder. AMD builds in about 5 minutes but qemu slows the arm generation down to 20 minutes.

**Pull request merged**
